[package]
name = "lwhlisp"
version = "0.7.1"
edition = "2021"

[dependencies]
ariadne = "0.1.5"
chumsky = "0.8.0"
color-eyre = "0.6.1"
gc = { version = "0.4.1", features = ["derive"] }
rustyline = "9.1.2"
